"""Initial database schema

Revision ID: 3be1cced8b11
Revises: 
Create Date: 2026-06-29 12:15:31.596506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3be1cced8b11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telemetry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sd_card_ok', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telemetry', schema=None) as batch_op:
        batch_op.drop_column('timestamp')
        batch_op.drop_column('sd_card_ok')

    # ### end Alembic commands ###
